# Generated by Django 3.1.2 on 2023-10-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(blank=True),
        ),
    ]
