# Generated by Django 3.1.2 on 2023-10-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_audiorecording'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioRecording',
        ),
    ]
