# Generated by Django 3.1.2 on 2023-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_audiorecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
