# Generated by Django 3.1.2 on 2023-10-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20231027_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chat'),
        ),
    ]
