# Generated by Django 3.1.2 on 2023-10-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20231027_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
