# Generated by Django 3.1.2 on 2023-10-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_conversation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created_time',
            field=models.TimeField(null=True),
        ),
    ]
